# Generated by Django 4.1 on 2023-10-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="myUploadFile",
            new_name="myUploadFiles",
        ),
    ]
