# Generated by Django 4.1 on 2023-10-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_myuploadfile_myuploadfiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuploadfiles",
            name="file_name",
        ),
    ]
