# Generated by Django 4.1 on 2023-10-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_myuploadfiles_file_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="myUploadFiles",
            new_name="uploadFileModel",
        ),
    ]
